# Generated by Django 4.2.7 on 2024-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookoutlet", "0002_books_author_books_is_bestselling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
