# Generated by Django 4.2.7 on 2024-03-11 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0004_author_alter_book_slug_alter_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="fist_name",
            new_name="first_name",
        ),
    ]
